// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyFlow.Context;

#nullable disable

namespace MoneyFlow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502003200_NuevaMigracion")]
    partial class NuevaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyFlow.Entities.Services", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.HasKey("ServiceID");

                    b.HasIndex("Userid");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MoneyFlow.Entities.Transactions", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Serviceid")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("Serviceid");

                    b.HasIndex("Userid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyFlow.Entities.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "Cris12@gmail.com",
                            Password = "Cris123",
                            UserName = "Cristopher Mariñez"
                        });
                });

            modelBuilder.Entity("MoneyFlow.Entities.Services", b =>
                {
                    b.HasOne("MoneyFlow.Entities.Users", "ObjUser")
                        .WithMany("IServices")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObjUser");
                });

            modelBuilder.Entity("MoneyFlow.Entities.Transactions", b =>
                {
                    b.HasOne("MoneyFlow.Entities.Services", "Objservice")
                        .WithMany()
                        .HasForeignKey("Serviceid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyFlow.Entities.Users", "ObjUser")
                        .WithMany("ITransactions")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObjUser");

                    b.Navigation("Objservice");
                });

            modelBuilder.Entity("MoneyFlow.Entities.Users", b =>
                {
                    b.Navigation("IServices");

                    b.Navigation("ITransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
